// Generated by rstantools.  Do not edit by hand.

/*
    MyStanPkg is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MyStanPkg is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with MyStanPkg.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_my_stan_model1_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 20> locations_array__ =
  {" (found before start of program)",
  " (in 'my_stan_model1', line 13, column 2 to column 15)",
  " (in 'my_stan_model1', line 14, column 2 to column 18)",
  " (in 'my_stan_model1', line 15, column 2 to column 22)",
  " (in 'my_stan_model1', line 19, column 2 to column 57)",
  " (in 'my_stan_model1', line 20, column 2 to column 66)",
  " (in 'my_stan_model1', line 21, column 2 to column 39)",
  " (in 'my_stan_model1', line 23, column 2 to column 39)",
  " (in 'my_stan_model1', line 24, column 2 to column 43)",
  " (in 'my_stan_model1', line 2, column 2 to column 22)",
  " (in 'my_stan_model1', line 3, column 8 to column 14)",
  " (in 'my_stan_model1', line 3, column 2 to column 33)",
  " (in 'my_stan_model1', line 4, column 2 to column 25)",
  " (in 'my_stan_model1', line 5, column 8 to column 17)",
  " (in 'my_stan_model1', line 5, column 2 to column 37)",
  " (in 'my_stan_model1', line 6, column 2 to column 26)",
  " (in 'my_stan_model1', line 7, column 2 to column 33)",
  " (in 'my_stan_model1', line 8, column 2 to column 29)",
  " (in 'my_stan_model1', line 9, column 2 to column 36)",
  " (in 'my_stan_model1', line 10, column 2 to column 34)"};
#include <stan_meta_header.hpp>
class model_my_stan_model1 final : public model_base_crtp<model_my_stan_model1> {
private:
  int N_drug;
  std::vector<double> drug_x_data;
  int N_placebo;
  std::vector<double> placebo_data;
  double prior_mu_drug_mean;
  double prior_mu_drug_sd;
  double prior_mu_placebo_mean;
  double prior_mu_placebo_sd;
  double prior_sigma_scale;
public:
  ~model_my_stan_model1() {}
  model_my_stan_model1(stan::io::var_context& context__, unsigned int
                       random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_my_stan_model1_namespace::model_my_stan_model1";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 9;
      context__.validate_dims("data initialization", "N_drug", "int",
        std::vector<size_t>{});
      N_drug = std::numeric_limits<int>::min();
      current_statement__ = 9;
      N_drug = context__.vals_i("N_drug")[(1 - 1)];
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "N_drug", N_drug, 0);
      current_statement__ = 10;
      stan::math::validate_non_negative_index("drug_x_data", "N_drug", N_drug);
      current_statement__ = 11;
      context__.validate_dims("data initialization", "drug_x_data", "double",
        std::vector<size_t>{static_cast<size_t>(N_drug)});
      drug_x_data = std::vector<double>(N_drug,
                      std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 11;
      drug_x_data = context__.vals_r("drug_x_data");
      current_statement__ = 12;
      context__.validate_dims("data initialization", "N_placebo", "int",
        std::vector<size_t>{});
      N_placebo = std::numeric_limits<int>::min();
      current_statement__ = 12;
      N_placebo = context__.vals_i("N_placebo")[(1 - 1)];
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "N_placebo", N_placebo,
        0);
      current_statement__ = 13;
      stan::math::validate_non_negative_index("placebo_data", "N_placebo",
        N_placebo);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "placebo_data",
        "double", std::vector<size_t>{static_cast<size_t>(N_placebo)});
      placebo_data = std::vector<double>(N_placebo,
                       std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 14;
      placebo_data = context__.vals_r("placebo_data");
      current_statement__ = 15;
      context__.validate_dims("data initialization", "prior_mu_drug_mean",
        "double", std::vector<size_t>{});
      prior_mu_drug_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 15;
      prior_mu_drug_mean = context__.vals_r("prior_mu_drug_mean")[(1 - 1)];
      current_statement__ = 16;
      context__.validate_dims("data initialization", "prior_mu_drug_sd",
        "double", std::vector<size_t>{});
      prior_mu_drug_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 16;
      prior_mu_drug_sd = context__.vals_r("prior_mu_drug_sd")[(1 - 1)];
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "prior_mu_drug_sd",
        prior_mu_drug_sd, 0);
      current_statement__ = 17;
      context__.validate_dims("data initialization", "prior_mu_placebo_mean",
        "double", std::vector<size_t>{});
      prior_mu_placebo_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 17;
      prior_mu_placebo_mean = context__.vals_r("prior_mu_placebo_mean")[(1 -
        1)];
      current_statement__ = 18;
      context__.validate_dims("data initialization", "prior_mu_placebo_sd",
        "double", std::vector<size_t>{});
      prior_mu_placebo_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 18;
      prior_mu_placebo_sd = context__.vals_r("prior_mu_placebo_sd")[(1 - 1)];
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "prior_mu_placebo_sd",
        prior_mu_placebo_sd, 0);
      current_statement__ = 19;
      context__.validate_dims("data initialization", "prior_sigma_scale",
        "double", std::vector<size_t>{});
      prior_sigma_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 19;
      prior_sigma_scale = context__.vals_r("prior_sigma_scale")[(1 - 1)];
      current_statement__ = 19;
      stan::math::check_greater_or_equal(function__, "prior_sigma_scale",
        prior_sigma_scale, 0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_my_stan_model1";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_my_stan_model1_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ mu_drug = DUMMY_VAR__;
      current_statement__ = 1;
      mu_drug = in__.template read<local_scalar_t__>();
      local_scalar_t__ mu_placebo = DUMMY_VAR__;
      current_statement__ = 2;
      mu_placebo = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      {
        current_statement__ = 4;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_drug,
                         prior_mu_drug_mean, prior_mu_drug_sd));
        current_statement__ = 5;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_placebo,
                         prior_mu_placebo_mean, prior_mu_placebo_sd));
        current_statement__ = 6;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma, 0,
                         prior_sigma_scale));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(drug_x_data,
                         mu_drug, sigma));
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(placebo_data,
                         mu_placebo, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_my_stan_model1_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double mu_drug = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      mu_drug = in__.template read<local_scalar_t__>();
      double mu_placebo = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      mu_placebo = in__.template read<local_scalar_t__>();
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      out__.write(mu_drug);
      out__.write(mu_placebo);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu_drug = DUMMY_VAR__;
      current_statement__ = 1;
      mu_drug = in__.read<local_scalar_t__>();
      out__.write(mu_drug);
      local_scalar_t__ mu_placebo = DUMMY_VAR__;
      current_statement__ = 2;
      mu_placebo = in__.read<local_scalar_t__>();
      out__.write(mu_placebo);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu_drug",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "mu_placebo",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu_drug = DUMMY_VAR__;
      current_statement__ = 1;
      mu_drug = context__.vals_r("mu_drug")[(1 - 1)];
      out__.write(mu_drug);
      local_scalar_t__ mu_placebo = DUMMY_VAR__;
      current_statement__ = 2;
      mu_placebo = context__.vals_r("mu_placebo")[(1 - 1)];
      out__.write(mu_placebo);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu_drug", "mu_placebo", "sigma"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu_drug");
    param_names__.emplace_back(std::string() + "mu_placebo");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu_drug");
    param_names__.emplace_back(std::string() + "mu_placebo");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu_drug\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu_placebo\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu_drug\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu_placebo\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_my_stan_model1_namespace::model_my_stan_model1;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_my_stan_model1_namespace::profiles__;
}
#endif
#endif
