name: Build MyStanPkg1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'  # or a specific version you want

      - name: Install build dependencies
        run: |
          install.packages('devtools')
          install.packages('rstantools')

      - name: Build the package
        run: |
          Rscript -e "devtools::build()"
          # Optionally, list the tarball produced:
          ls -lh *.tar.gz
