name: Build MyStanPkg1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
          
      - name: Install remotes and devtools and rstantools
        run: |
          Rscript -e "install.packages('remotes', repos='https://cloud.r-project.org')"
          Rscript -e "remotes::install_cran('devtools', dependencies=TRUE, repos='https://cloud.r-project.org')"
          Rscript -e "remotes::install_cran('rstantools', dependencies=TRUE, repos='https://cloud.r-project.org')"

      - name: Build the package
        run: |
          Rscript -e "devtools::build()"
          ls -lh *.tar.gz
