name: Build MyStanPkg1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install missing dependencies for devtools
        run: |
          Rscript -e "install.packages(c('usethis', 'pkgdown', 'rcmdcheck', 'rversions', 'urlchecker'), repos='https://cloud.r-project.org')"

      - name: Install devtools and rstantools
        run: |
          Rscript -e "install.packages('devtools', repos='https://cloud.r-project.org', dependencies=TRUE)"
          Rscript -e "install.packages('rstantools', repos='https://cloud.r-project.org', dependencies=TRUE)"

      - name: Build the package
        run: |
          Rscript -e "devtools::build()"
          ls -lh *.tar.gz
