name: Build MyStanPkg1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libgit2-dev \
            libmagick++-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            ghostscript \
            libharfbuzz-dev \
            libfribidi-dev

      - name: Install dependencies and Build the package
        run: |
          # Install all R packages (including devtools, pkgdown, rstantools) in one go
          Rscript -e "install.packages(c('pkgdown','rcmdcheck','rversions','urlchecker','curl','credentials','httr2','gert','gh','usethis','remotes','devtools','rstantools'), repos='https://cloud.r-project.org', dependencies=TRUE)"
          
          # Build your package in the same R session, ensuring devtools is loaded
          Rscript -e "library(devtools); devtools::build()"
          
          # List the tarball created
          ls -lh *.tar.gz
